```{r}
library(tidyverse)

#Create variables from PennData 12/1 Export
PaSecureID <- sample(1111111:9999999,1000)
StdttNameFirst <- c("First")
StdtNameMiddle <- c("Middle")
StdttNameLast <- c("Last")
StdtDOB <- c("2004-01-12")
StdtDOB <- as.Date(StdntDOB)
StdtPrmryDis <- sample(1:12,1000, replace=TRUE)
StdtGender <- sample(1:2,1000,replace = TRUE)
StdtLEA <- sample(1:50,1000,replace = TRUE)
StdtSchool <- sample(1:300,1000,replace = TRUE)
StdtEth <- sample(1:7,1000,replace = TRUE)
ExitStatus <- sample(1:10,1000, replace = TRUE)
#Diploma, GED, Aged out, dropped out, transfer to gen ed, moved out of state - continuing, died, moved within state - continuing (1:9,99 becomes 1:10)
PennData <- data.frame(
  StdtNameFirst,
  StdtNameMiddle,
  StdtNameLast,
  StdtDOB,
  StdtPrmryDis,
  StdtGender,
  StdtLEA,
  StdtSchool,
  StdtEth,
  ExitStatus
)

```

```{r}
#Gathered from the SAAFP 2.0 - Exit Data
StdtStreet <- c("123 Main Street")
StdtCity <- c("Anywhere")
StdtZip <- c(15001)
StdtState <- c("PA") #vector of 50 states, drop-down
StdtHomePhone <- c("111-111-1111")
StdtCellPhone <- c("222-222-2222")
StdtEmail <- c("Test1@gmail.com") #NOT school email
PCFirstName <- c("George")
PCLastName <- c("Washington")
PCStreet <- c("123 Side Street")
PCCITY <- c("Somewhere")
PCHomePhone <- c("333-333-3333")
PCCellPhone <- c("444-444-4444")
PCEmail <- c("Test2@gmail.com")

#Gathered from SAAFP 2.0

  
#Gathered through I-14 Survey
#14.A
PSE_STATUS <- sample(1:2,8950,replace=TRUE)
PSE_TERM <- ifelse(PSE_STATUS==2,sample(1:2,8950,replace=TRUE), print(""))

#OSEP / NTACT's categories may not be enough for PA's needs, we could add a 6th option for certificate programs (e.g., bootcamps, ect.) or more as needed.

PSE_PGRM <- ifelse(PSE_STATUS==2,sample(1:6,8950,replace=TRUE), print(""))

#14.B
EMPLY_STATUS <- sample(1:2,8950,replace=TRUE)

#the following variables combine to measure CIE
EMPLY_3MNTHs <- ifelse(EMPLY_STATUS==2,sample(1:2,8950,replace=TRUE), print(""))

EMPLY_20Hrs <- ifelse(EMPLY_STATUS==2,sample(1:2,8950,replace=TRUE), print (""))

EMPLY_WAGE <- ifelse(EMPLY_STATUS==2,sample(1:2,8950,replace=TRUE), print(""))

EMPLY_INTERACT <- ifelse(EMPLY_STATUS==2,sample(1:2,8950,replace=TRUE), print(""))

EMPLY_PROMO <- ifelse(EMPLY_STATUS==2,sample(1:2,8950,replace=TRUE), print(""))

COMPANY_NAME <- ifelse(EMPLY_STATUS==2,"Example LLC.", print(""))

COMPANY_TYPE <- ifelse(EMPLY_STATUS==2,sample(1:8,8950,replace=TRUE), print(""))

CAREER_CLUSTER <- ifelse(EMPLY_STATUS==2,sample(1:16,8950,replace=TRUE), print(""))

EQUAL_COMP <- ifelse(EMPLY_STATUS==2,sample(1:2,8950,replace=TRUE), print(""))

BENEFITS <- ifelse(EMPLY_STATUS==2,sample(1:2,8950,replace=TRUE), print(""))

#I.14 Status
HigherEd <- if(PSE_STATUS==2 
               & PSE_STATUS==1
               | PSE_STATUS==2
               & PSE_PGRM==4){print(1)} else {print(0)}

CIE <- if(EMPLY_STATUS==2
          & !is.null(EMPLY_3MNTHs) 
          & !is.null(EMPLY_20Hrs) 
          & !is.null(EMPLY_WAGE) 
          & !is.null(EMPLY_INTERACT) 
          & !is.null(EMPLY_PROMO) 
          & (COMPANY_TYPE==1:5)
          & !is.null(EQUAL_COMP)
          & !is.null(BENEFITS)) {print(1)} else {print(0)}

OTHERPSE <- if(PSE_STATUS==2 
               & PSE_TERM==2 
               | PSE_PGRM==1
               | PSE_PGRM==2
               | PSE_PGRM==3
               | PSE_PGRM==5
               | PSE_PGRM==6) {print(1)} else {print(0)}

OTHEREMPLY <- if(EMPLY_STATUS==2
                 | EMPLY_3MNTHs==2
                 | EMPLY_20Hrs==2
                 | EMPLY_WAGE==2
                 | EMPLY_INTERACT==2
                 | EMPLY_PROMO==2
                 | COMPANY_TYPE==1:8
                 & EQUAL_COMP==1
                 & BENEFITS==1){print(1)} else {print(0)}

NOTENGAGED <- if(PSE_STATUS==1
                 & EMPLY_STATUS==1
                 & EMPLY_3MNTHs==1){print(1)} else {print(0)}

sampledata <- data.frame(
  School_Name,
  School_District_Code,School_Geo,
  Student_Last,
  Student_First,
  Student_Middle,
  Stdt_Dis_ID,
  Stdt_State_ID,
  Stdt_Survey_ID,
  Stdt_DOB_MM,
  Stdt_DOB_DD,
  Stdt_DOB_YYYY,
  Stdt_EXIT_MM,
  Stdt_EXIT_DD,
  Stdt_EXIT_YYYY,
  Stdt_Primary_Dis,
  Stdt_Gender,
  Stdt_Race_Eth,
  Stdt_Exit_Status,
  PSE_STATUS,
  PSE_TERM,
  PSE_PGRM,
  EMPLY_STATUS,
  EMPLY_3MNTHs,
  EMPLY_20Hrs,
  EMPLY_WAGE,
  EMPLY_INTERACT,
  EMPLY_PROMO,
  COMPANY_TYPE,
  EQUAL_COMP,
  BENEFITS
  )

#calculate percentages for 14 A, B and C

percentageA <- (sum(HigherEd))/(sum(Stdt_Survey_ID))*100

percentageB <- (sum(HigherED,CIE))/(sum(Stdt_Survey))*100
                
percentageC



```

